CREATE TABLE clienti_jpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE utenti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    ruolo VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT utenti_ruolo_check
        CHECK (ruolo IN ('USER', 'ADMIN'))
);

CREATE TABLE ordini_jpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stato VARCHAR(255),
    cliente_id BIGINT,
    CONSTRAINT fk_ordini_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clienti_jpa(id)
);

CREATE TABLE profilo_cliente_jpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono VARCHAR(255),
    cliente_id BIGINT UNIQUE,
    CONSTRAINT fk_profilo_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clienti_jpa(id)
);